[workspace]
authors = ["Andrew Jensen <contact@ajensen.org>"]
channels = ["conda-forge"]
name = "2d-point-annotator"
platforms = ["linux-64", "win-64", "osx-arm64"]
version = "0.1.0"

[tasks]
annotator = {cmd = "python ./main.py"}

[dependencies]
numpy = ">=2.3.5,<3"
pandas = ">=2.3.3,<3"
pillow = ">=12.0.0,<13"
opencv = ">=4.12.0,<5"
