[workspace]
authors = ["Andrew Jensen <contact@ajensen.org>"]
channels = ["conda-forge"]
name = "2d-point-annotator"
platforms = ["linux-64", "win-64", "osx-arm64"]
version = "0.1.0"

[tasks]
annotator = {cmd = "python ./src/main.py"}

fc-cache = { cmd = "fc-cache -r", env = { FONTCONFIG_PATH = "$CONDA_PREFIX/etc/fonts", FC_CONFIG_FILE = "$CONDA_PREFIX/etc/fonts/fonts.conf" } }

# Quick check: prove the env can see DejaVu.
fc-check = { cmd = "bash -lc 'fc-list | grep -i dejavu | head -n 20'", env = { FONTCONFIG_PATH = "$CONDA_PREFIX/etc/fonts", FC_CONFIG_FILE = "$CONDA_PREFIX/etc/fonts/fonts.conf" } }

run = { cmd = "python ./main.py", env = { FONTCONFIG_PATH = "$CONDA_PREFIX/etc/fonts", FC_CONFIG_FILE = "$CONDA_PREFIX/etc/fonts/fonts.conf" } }


[dependencies]
numpy = ">=2.3.5,<3"
pandas = ">=2.3.3,<3"
pillow = ">=12.0.0,<13"
opencv = ">=4.12.0,<5"
python = ">=3.13.11,<3.14"
fontconfig = ">=2.15.0,<3"
freetype = ">=2.14.1,<3"
xorg-libxrender = ">=0.9.12,<0.10"
font-ttf-roboto = ">=3.15,<4"
open-fonts = ">=0.7.0,<0.8"
font-ttf-dejavu-sans-mono = ">=2.37,<3"
font-ttf-dejavu = ">=2.37,<3"
tk = ">=8.6.13,<9"
polars = ">=1.37.1,<2"
sqlite = ">=3.51.2,<4"
msgraph-sdk = ">=1.48.0,<2"

[target.linux-64.dependencies]
xorg-libxft = ">=2.3.9,<3"
xorg-libx11 = ">=1.8.12,<2"
xorg-libxext = ">=1.3.6,<2"
