exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".pixi",
    "__pypackages__",
    "_build",
    "buck-out",
    "dist",
    "node_modules",
    "venv",
    "docs"
]
target-version = "py313"
line-length = 88

[lint]
select =[
    "E", #pycodestyle
    "W", # pycodestyle
    "B", # flake8-bugbear
    "F", #pyflakes
    "C",
    "PTH", # flake8-use-pathlib
    "PT", # flake8-pytest-style
    #"I", # isort
    "ARG", # flake8-unused-arguments
    "ANN", # flake8-annotations
    #"N", # pep8-naming
    "S", # flake8-bandit
]

ignore =[
    "D",
    #"E501", # line-too-long
    "F401", # unused-import
    "F841", # unused-variable
    "N803", # case in variables
    "ANN401", # Any type
]

fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
pycodestyle.max-doc-length = 88


[lint.flake8-annotations]
suppress-none-returning = true

[format]
docstring-code-format = true
docstring-code-line-length = "dynamic"
